# K-Nearest Neighbor(KNN) Algorithm

In [36]:
# Step 1: Import Libraries
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.metrics import accuracy_score, classification_report,precision_score,recall_score,f1_score
import seaborn as sns

In [7]:
# Step 2: Load Dataset
data = load_breast_cancer()

X = data.data
y = data.target

In [8]:
# Step 3: Split Data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
# Step 4: Feature Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
# Step 5: Train KNN Model
knn = KNeighborsClassifier(
    n_neighbors=5,      # K value
    weights='uniform',  # uniform or distance
    metric='minkowski', # distance metric
    p=2                 # p=2 Euclidean, p=1 Manhattan
)

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [14]:
# Step 6: Prediction
y_pred = knn.predict(X_test)

In [15]:
# Step 7: Evaluation
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))

Accuracy: 0.9473684210526315
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

# IRIS DATASET

In [21]:
df = sns.load_dataset('iris')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [22]:
X = df.drop('species',axis=1)
y = df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
knn = KNeighborsClassifier(
    n_neighbors=5,      # K value
    weights='uniform',  # uniform or distance
    metric='minkowski', # distance metric
    p=2                 # p=2 Euclidean, p=1 Manhattan
)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))

Accuracy: 1.0
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

# Pima Indians Diabetes Prediction

In [25]:
import pandas as pd 
df = pd.read_csv('./Datasets/diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76.0,48,180.0,32.9,0.171,63,0
764,2,122,70.0,27,102.5,36.8,0.340,27,0
765,5,121,72.0,23,112.0,26.2,0.245,30,0
766,1,126,60.0,32,169.5,30.1,0.349,47,1
767,1,93,70.0,31,102.5,30.4,0.315,23,0

In [35]:
X = df.drop('Outcome',axis=1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
for i in range(1,8,2):
    knn = KNeighborsClassifier(
        n_neighbors=i,      # K value
        weights='uniform',  # uniform or distance
        metric='minkowski', # distance metric
        p=2                 # p=2 Euclidean, p=1 Manhattan
    )
    print('K Value : ',i)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test,y_pred)
    recall = recall_score(y_test,y_pred)
    f1 = f1_score(y_test,y_pred)


    print("Accuracy:", accuracy)
    print("precision:", precision)
    print("recall:", recall)
    print("f1 Score:", f1)
    print(classification_report(y_test, y_pred))

K Value :  1
Accuracy: 0.7597402597402597
precision: 0.6607142857142857
recall: 0.6727272727272727
f1 Score: 0.6666666666666666
              precision    recall  f1-score   support

           0       0.82      0.81      0.81        99
           1       0.66      0.67      0.67        55

    accuracy                           0.76       154
   macro avg       0.74      0.74      0.74       154
weighted avg       0.76      0.76      0.76       154

K Value :  3
Accuracy: 0.8051948051948052
precision: 0.6984126984126984
recall: 0.8
f1 Score: 0.7457627118644068
              precision    recall  f1-score   support

           0       0.88      0.81      0.84        99
           1       0.70      0.80      0.75        55

    accuracy                           0.81       154
   macro avg       0.79      0.80      0.79       154
weighted avg       0.81      0.81      0.81       154

K Value :  5
Accuracy: 0.7987012987012987
precision: 0.6935483870967742
recall: 0.7818181818181819
f1 Score: 0.7350427350427351
              precision    recall  f1-score   support

           0       0.87      0.81      0.84        99
           1       0.69      0.78      0.74        55

    accuracy                           0.80       154
   macro avg       0.78      0.79      0.79       154
weighted avg       0.81      0.80      0.80       154

K Value :  7
Accuracy: 0.7922077922077922
precision: 0.7017543859649122
recall: 0.7272727272727273
f1 Score: 0.7142857142857143
              precision    recall  f1-score   support

           0       0.85      0.83      0.84        99
           1       0.70      0.73      0.71        55

    accuracy                           0.79       154
   macro avg       0.77      0.78      0.78       154
weighted avg       0.79      0.79      0.79       154

# California Housing (Regression)

In [37]:
from sklearn.datasets import fetch_california_housing

In [38]:
data = fetch_california_housing()
data.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [39]:
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [40]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
for i in range(1,8,2):
    model = KNeighborsRegressor(n_neighbors=i)
    print('K Value : ',i)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print("MAE :", mae)
    print("MSE :", mse)
    print("RMSE:", rmse)
    print("R²  :", r2)
    print("-" * 40)

K Value :  1
MAE : 0.5361632582364342
MSE : 0.6690121695201793
RMSE: 0.8179316411046703
R²  : 0.48946307555198154
----------------------------------------
K Value :  3
MAE : 0.4599198611111111
MSE : 0.4666634350517549
RMSE: 0.6831276857599572
R²  : 0.6438795499720962
----------------------------------------
K Value :  5
MAE : 0.4461535271317829
MSE : 0.4324216146043236
RMSE: 0.6575877238850522
R²  : 0.6700101862970989
----------------------------------------
K Value :  7
MAE : 0.4440386652131783
MSE : 0.42833350309961193
RMSE: 0.6544719268995516
R²  : 0.673129908134017
----------------------------------------